name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Frontend Docker image
      run: |
        cd frontend
        docker build -t saetovdinar/reactdiplom-frontend .

    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t saetovdinar/reactdiplom-backend .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Frontend Docker image
      run: |
        docker push saetovdinar/reactdiplom-frontend

    - name: Push Backend Docker image
      run: |
        docker push saetovdinar/reactdiplom-backend
