
name: CI/CD Pipeline

on:
  push:
    branches:
      - main  
permissions:
  contents: write  # Дает разрешение на запись в репозиторий

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Frontend Docker image
      run: |
        cd frontend
        docker build -t saetovdinar/reactdiplom-frontend .

    - name: Build Backend Docker image
      run: |
        cd backend
        docker build -t saetovdinar/reactdiplom-backend .

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Frontend Docker image
      run: |
        docker push saetovdinar/reactdiplom-frontend

    - name: Push Backend Docker image
      run: |
        docker push saetovdinar/reactdiplom-backend

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'  

    - name: Install dependencies
      run: npm install
      working-directory: frontend  # Укажи путь к папке фронтенда

    - name: Build Frontend
      run: npm run build
      working-directory: frontend  # Укажи путь к папке фронтенда
    


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        publish_dir: frontend/out  

